### ISSUE TITLE
Изучить медиа

### ISSUE THREAD

**Issue by Alex-Vay** [Alex-Vay/JustLibrary#3]
Рассмотреть следующие пункты

- Способы организации, хранения и предствления медиа контента
- Какой функционал и как предствляют другие электронные библиотеки
- Особенности предоствления книги, как это сделано у других и как можем сделать мы

**Comment by KiselevEgor** [comment]
[Киселев Медасистемы.docx](https://github.com/Alex-Vay/JustLibrary/files/13343790/default.docx)
[Киселев Медиасистема.pptx](https://github.com/Alex-Vay/JustLibrary/files/13343791/default.pptx)

**Comment by KiselevEgor** [comment]
[Киселев Е. А. выводы 1.docx](https://github.com/Alex-Vay/JustLibrary/files/13344769/1.docx)

**Comment by KiselevEgor** [comment]
[Киселев Медиасистема(обновленная версия).pptx](https://github.com/Alex-Vay/JustLibrary/files/13353686/default.pptx)

**Comment by KiselevEgor** [comment]
https://drive.google.com/file/d/1Bj-nTOfTJAFT_eHhCDxmwsC_l03Ah1cU/view[](url)

 Видеопрезентация по теме "Медиасистемы" . Киселев Е. А
