### ISSUE TITLE
Изучить электронные библиотеки

### ISSUE THREAD

**Issue by Alex-Vay** [Alex-Vay/JustLibrary#4]
Рассмотреть следующие пунткы

- что такое электронная библиотека и что она из себя представляет
- рассмотреть аналоги, в том числе косвенные с выводами, что у них есть, чего нет, что можно перенять, чем будем отличаться (полноценный обзор 2-4 приложения, для каждого выводы, интересный функционал)

**Comment by Kirill-Eltsov** [comment]
[Выводы_Ельцов_Крилл_Павлович_Электронные_библиотеки.docx](https://github.com/Alex-Vay/JustLibrary/files/13348644/_._._._._.docx)
[Ельцов_Крилл_Павлович_Электронные_библиотеки.docx](https://github.com/Alex-Vay/JustLibrary/files/13348642/_._._._.docx)
[Ельцов_Крилл_Павлович_Электронные_библиотеки.pptx](https://github.com/Alex-Vay/JustLibrary/files/13348643/_._._._.pptx)

**Comment by Kirill-Eltsov** [comment]
https://drive.google.com/drive/folders/1jm3RyBIf6dhLifGItdtaagWot72klWye
Видеопрезентация
